apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\angel\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\angel\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/elaborato-ds-mainetwork: "true"
        io.kompose.service: api-service
    spec:
      containers:
        - env:
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  key: API_KEY
                  name: C:\Users\angel\IdeaProjects\Elaborato-DS\-env
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_GROUP
              value: group
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PASSWORD
                  name: C:\Users\angel\IdeaProjects\Elaborato-DS\-env
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_USERNAME
                  name: C:\Users\angel\IdeaProjects\Elaborato-DS\-env
            - name: MYSQL_DATABASE
              value: api
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_USER
              value: an
          image: api-service
          name: api-service
          ports:
            - containerPort: 5002
              hostPort: 5002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
