version: '3'

volumes:
  mysql_data_users:
  mysql_data_subscription:

services:
  mysql_users:
    image: mysql:latest
    container_name: mysql_users
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'users'  # Nome del database per il servizio auth
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
    ports:
      - "9090:3306"
    volumes:
      - mysql_data_users:/var/lib/mysql
    restart: always

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      MYSQL_DATABASE: 'users'  # Utilizza lo stesso database 'auth' per il servizio auth
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql_users

  mysql_subscription:
    image: mysql:latest
    container_name: mysql_subscription
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'subscription'  # Nuovo database per il serviziometeo
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
    ports:
      - "9091:3306"
    volumes:
     - mysql_data_subscription:/var/lib/mysql
    restart: always

  subscription_service:
    build:
      context: subscription_service
      dockerfile: Dockerfile
    container_name: subscription_service
    environment:
      MYSQL_DATABASE: 'subscription'  # Nuovo database per il servizio meteo
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mysql_subscription





