version: '3'

services:
  mysql_users:
    image: mysql:8.0
    container_name: mysql_users
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'users'  # Nome del database per il servizio auth
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./users.sql:/docker-entrypoint-initdb.d/:ro
    restart: always

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      MYSQL_DATABASE: 'users'  # Utilizza lo stesso database 'auth' per il servizio auth
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql_users

  mysql_weather:
    image: mysql:8.0
    container_name: mysql_weather
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'user_preferences'  # Nuovo database per il serviziometeo
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./user_preferences.sql:/docker-entrypoint-initdb.d/:ro
    restart: always

  weather_service:
    build:
      context: ./weather_service
      dockerfile: Dockerfile
    container_name: weather_service
    environment:
      MYSQL_DATABASE: 'user_preferences'  # Nuovo database per il servizio meteo
      MYSQL_USER: 'an'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mysql_weather

volumes:
  mysql_data:




