# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier_service/flight.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnotifier_service/flight.proto\x12\nflightdata\"&\n\x11\x46lightDataRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"*\n\x17NotifyFlightDataSuccess\x12\x0f\n\x07message\x18\x01 \x01(\t2i\n\x11\x46lightDataService\x12T\n\x0eSendFlightData\x12\x1d.flightdata.FlightDataRequest\x1a#.flightdata.NotifyFlightDataSuccessb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifier_service.flight_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FLIGHTDATAREQUEST']._serialized_start=45
  _globals['_FLIGHTDATAREQUEST']._serialized_end=83
  _globals['_NOTIFYFLIGHTDATASUCCESS']._serialized_start=85
  _globals['_NOTIFYFLIGHTDATASUCCESS']._serialized_end=127
  _globals['_FLIGHTDATASERVICE']._serialized_start=129
  _globals['_FLIGHTDATASERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
