apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: elaborato-ds-api_service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MYSQL_DATABASE
              value: api
            - name: MYSQL_USER
              value: an
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_GROUP
              value: group

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  .env: TUFJTF9VU0VSTkFNRTonYW5nZWxvLWNvY3V6emFAbGliZXJvLml0Jw0KTUFJTF9QQVNTV09SRDonQmVzdGZsaWdodHMxMjMhJw0KQVBJX0tFWT0ncUxzTFZMOG9DSHAzcmlQMGxiYjNQVGN6MFROYzNyLVknDQo=
