apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: "nginx"
  rules:
    - host: localhost
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /auth(/|$)(.*)
            backend:
              service:
                name: microuser-service #nome del microservizio auth
                port:
                  number: 5000

          - pathType: ImplementationSpecific
            path: /subscription(/|$)(.*)
            backend:
              service:
                name: microphoto-service #nome del microservizio auth
                port:
                  number: 5000

          - pathType: ImplementationSpecific
            path: /sla(/|$)(.*)
            backend:
              service:
                name: microphoto-service #nome del microservizio auth
                port:
                  number: 5000