apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: angelo3100/elaborato-ds-api_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_SERV_NAME
              value: "mysql-api"
            - name: API_KEY
              value: 'qLsLVL8oCHp3riP0lbb3PTcz0TNc3r-Y'
            - name: MYSQL_DATABASE
              value: api
            - name: MYSQL_USER
              value: an
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_GROUP
              value: group
          command: ["python", "-u", "api.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000