apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: angelo3100/elaborato-ds-auth_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: API_KEY
              value: 'qLsLVL8oCHp3riP0lbb3PTcz0TNc3r-Y'
            - name: MYSQL_SERV_NAME
              value: "mysql-users"
            - name: MYSQL_DATABASE
              value: users
            - name: MYSQL_USER
              value: an
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: SECRET_KEY
              value: chiavesegreta
          command: ["flask", "--app", "auth", "run", "--host=0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  .env: TUFJTF9VU0VSTkFNRTonYW5nZWxvLWNvY3V6emFAbGliZXJvLml0Jw0KTUFJTF9QQVNTV09SRDonQmVzdGZsaWdodHMxMjMhJw0KQVBJX0tFWT0ncUxzTFZMOG9DSHAzcmlQMGxiYjNQVGN6MFROYzNyLVknDQo=
