apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-service
  template:
    metadata:
      labels:
        app: notifier-service
    spec:
      containers:
        - name: notifier-service
          image: angelo3100/elaborato-ds-notifier_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_SERV_NAME
              value: "mysql-bestflights"
            - name: MYSQL_DATABASE
              value: bestflights
            - name: MYSQL_USER
              value: an
            - name: MYSQL_PASSWORD
              value: '12345'
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka:9092'
            - name: KAFKA_GROUP_ID
              value: group
            - name: MAIL_SERVER
              value: 'smtp.libero.it'
            - name: MAIL_PORT
              value: '465'
            - name: MAIL_USE_TLS
              value: 'False'
            - name: MAIL_USE_SSL
              value: 'True'
            - name: MAIL_USERNAME
              value: 'angelo-cocuzza@libero.it'


            - name: MAIL_PASSWORD
              value: 'Bestflights123!'

            - name: MAIL_DEFAULT_SENDER
              value: 'angelo-cocuzza@libero.it'

          command: ["python", "-u", "notifier.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
